# Generated by Django 5.1.1 on 2024-11-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_id_number',
            field=models.CharField(default='default_voter_id', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='apartment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_of_registration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='voter',
            name='party_affiliation',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v20state',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21primary',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21town',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v22general',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v23town',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_score',
            field=models.IntegerField(),
        ),
    ]
