# Generated by Django 5.1.1 on 2024-12-05 20:49

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='season',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=25),
        ),
    ]
